services:
  app:
    build:
      context: .  # Build from the current directory (which should contain the Dockerfile)
    image: note-backend  # Tag for the image that will be built
    ports:
      - "5000:5000"  # Use the PORT variable from the .env file
    env_file:
      - .env  # Load environment variables from .env file
    volumes:
      - .:/app  # Mount the current directory to /app inside the container (optional)
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Use bridge network for local communication

